version: "3.8"

services:
  smart_auto_api:
    build: .
    image: smart_auto_api:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=staging
      - PORT=8080
      - API_VERSION=1.0.0
      - LOG_LEVEL=info
      - MONGODB_URI=mongodb://smart_auto_api_mongodb:27017/smart_auto_api_staging
      - JWT_SECRET=secret
      - JWT_ALGO=HS256
      - JWT_EXPIRES_IN="10 minutes"
      - EMAIL_USERNAME=
      - EMAIL_PASSWORD=
      - EMAIL_HOST=
      - EMAIL_PORT=
      - AUTH_USER=matthewnte1@gmail.com
      - CLIENT_ID=377135696774-da1b63u8m2qfio4jj7vaa9vef2lni5er.apps.googleusercontent.com
      - CLIENT_SECRET=i6bmt4yAc1_h5NUxUZoViOGP
      - REDIRECT_URI=https://developers.google.com/oauthplayground
      - REFRESH_TOKEN=1//04XclJ6mgizRcCgYIARAAGAQSNwF-L9IrQdICbQX5XkIS0EaqM9fEA2z5DT-xZkkoYqLkFsIXCLCCptefpLfSrL4kKXxHxwb_ft8
      - AGENDA_DB_COLLECTION=
      - AGENDA_POOL_TIME=
      - AGENDA_CONCURRENCY=
    volumes:
      - .:/app
    links:
      - smart_auto_api_mongodb

  # docker run -it --rm -p 27017:27017 --name mongodb -v ~/projects/local_mongo/data/db:/data/db mongo
  smart_auto_api_mongodb:
    image: mongo
    container_name: smart_auto_api_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data:
