version: "3.8"

services:
  smart_auto_api:
    build: .
    image: smart_auto_api:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=staging
      - PORT=8080
      - API_VERSION=1.0.0
      - LOG_LEVEL=info
      - MONGODB_URI=mongodb://smart_auto_api_mongodb:27017/smart_auto_api_staging
      - JWT_SECRET=secret
      - JWT_ALGO=HS256
      - JWT_EXPIRES_IN="10 minutes"
      - EMAIL_USERNAME=
      - EMAIL_PASSWORD=
      - EMAIL_HOST=
      - EMAIL_PORT=
      - GOOGLE_AUTH_USER=matthewnte1@gmail.com
      - GOOGLE_CLIENT_ID=377135696774-da1b63u8m2qfio4jj7vaa9vef2lni5er.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=i6bmt4yAc1_h5NUxUZoViOGP
      - GOOGLE_REDIRECT_URI=https://developers.google.com/oauthplayground
      - GOOGLE_REFRESH_TOKEN=1//04XclJ6mgizRcCgYIARAAGAQSNwF-L9IrQdICbQX5XkIS0EaqM9fEA2z5DT-xZkkoYqLkFsIXCLCCptefpLfSrL4kKXxHxwb_ft8
      - AUTH0_CLIENT_ID=E9e7S8TNdc1kdxGAdZwBnhZl84Hf2LJg
      - AUTH0_DOMAIN=dev-1mhehu-j.us.auth0.com
      - AUTH0_VERSION=2
      - AUTH0_CLIENT_SECRET=RUCg8eyZU4jU8TAZ_CeFP5BC3oKs3jJaMq2qgXL5g5Syog0cCc9koyolcuZBpOwX
      - AUTH0_RPM=5
      - AUTH0_JWKS_URI=https://dev-1mhehu-j.us.auth0.com/.well-known/jwks.json
      - AUTH0_AUD=https://howmies-smart-auto/dealer
      - AUTH0_ISS=https://dev-1mhehu-j.us.auth0.com/
      - AUTH0_ALGO=RS256
      - SESSION_SECRET=584bb84c275c124ba925d6aa6c0ff4493f0f49b3836e8ee6d591aa75d79c01d4
      - AUTH0_CALLBACK_URL=http://localhost:$PORT/api/v1.0.0/auth/login/callback
      - CLIENT_BASEURL=http://localhost:$PORT/api/v1.0.0
      - AGENDA_DB_COLLECTION=
      - AGENDA_POOL_TIME=
      - AGENDA_CONCURRENCY=
    volumes:
      - .:/app
    links:
      - smart_auto_api_mongodb

  # docker run -it --rm -p 27017:27017 --name mongodb -v ~/projects/local_mongo/data/db:/data/db mongo
  smart_auto_api_mongodb:
    image: mongo
    container_name: smart_auto_api_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data:
